version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: wildberries
    ports:
      - "5432:5432"
    volumes:
      - ./database-data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: vbg911@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "5050:80"


  nats-streaming:
    image: nats-streaming:latest
    restart: always
    ports:
      - "4222:4222"
